name: House Price Prediction Analysis

on: 
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Choose the appropriate Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas seaborn matplotlib scikit-learn

    - name: Run Python script
      run: model/main.py

    - name: Display model metrics and images using CML
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml-send-comment '## Model Metrics\n| Model | Mean MSE |\n|---|---|\n| Linear Regression | 123.45 |\n\n![Pairplot](pairplot.png)\n\n![Correlation Matrix](correlation_heatmap.png)'
