name: House Price Prediction Analysis

on: 
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-agastya

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-github-actions@v2
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Choose the appropriate Python version

    - name: Create virtual environment
      run: python -m venv myenv

    - name: Activate the virtual environment
      run: source myenv/bin/activate

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Change permissions of model/main.py
      run: chmod +x model/main.py
      
    - name: Run Python script
      run: python model/main.py

    # - name: Display model metrics and images using CML
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     cml-send-comment '## Model Metrics\n| Model | Mean MSE |\n|---|---|\n| Linear Regression | 123.45 |\n\n![Pairplot](pairplot.png)\n\n![Correlation Matrix](correlation_heatmap.png)'
    



    # Show file path and report contents
    - name: Show file path and report contents
      run: |
        echo "File path: ${{ github.workspace }}/report.md"
        echo "Report contents:"
        cat "${{ github.workspace }}/report.md"
        
    - name: Set Git Config
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
    # Create a new branch or checkout an existing branch
    - name: Create or checkout branch
      run: |
        # git checkout -b experiment-1 # Replace 'new-branch-name' with your desired branch name
        # git branch  # Optional: Check the current branch
        git checkout experiment-1
    # Git commands to add, commit, and push changes on the branch
    - name: Git add, commit, and push
      run: |
        git add report.md
        git commit -m "Update report.md [skip ci]" || echo "No changes to commit"
        git push origin experiment-1  
        
    - name: Commit report.md
      run: |
        git add report.md
        git commit -m "Update report.md [skip ci]" || echo "No changes to commit"
        git push
