name: House Price Prediction Analysis

on: 
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Choose the appropriate Python version

    - name: Create virtual environment
      run: python -m venv myenv

    - name: Activate the virtual environment
      run: source myenv/bin/activate

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Change permissions of model/main.py
      run: chmod +x model/main.py
      
    - name: Run Python script
      run: python model/main.py

    - name: Display model metrics and images using CML
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml-send-comment '## Model Metrics\n| Model | Mean MSE |\n|---|---|\n| Linear Regression | 123.45 |\n\n![Pairplot](pairplot.png)\n\n![Correlation Matrix](correlation_heatmap.png)'
